### PR TITLE
Attempt to fix #25. Process too long Strings before translating into Java Bytecode.

### LINKED ISSUE #25: not enough space for reading instruction on v53
```
ubuntu@fv48:~$ sh dex-tools-2.2-SNAPSHOT/d2j-dex2jar.sh pico.apk
dex2jar pico.apk -> ./pico-dex2jar.jar
GLITCH: 0004 L_a/a/_a;.<init>()V | not enough space for reading instruction
GLITCH: 000c L_/1;.<init>()V | not enough space for reading instruction
Applying workaround to method L_a/a/_a;#___a with original signature null by changing its types to java.lang.Object.
java.lang.IllegalArgumentException
        at org.objectweb.asm.ByteVector.putUTF8(ByteVector.java:213)
        at org.objectweb.asm.ClassWriter.newUTF8(ClassWriter.java:1092)
        at org.objectweb.asm.MethodWriter.<init>(MethodWriter.java:469)
        at org.objectweb.asm.ClassWriter.visitMethod(ClassWriter.java:793)
        at org.objectweb.asm.ClassVisitor.visitMethod(ClassVisitor.java:305)
        at org.objectweb.asm.commons.RemappingClassAdapter.visitMethod(RemappingClassAdapter.java:99)
        at org.objectweb.asm.ClassVisitor.visitMethod(ClassVisitor.java:305)
        at com.googlecode.d2j.dex.Dex2Asm.collectBasicMethodInfo(Dex2Asm.java:285)
        at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:611)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:469)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:380)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:508)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:180)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:280)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:112)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

ubuntu@fv48:~$ java --version
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```
apk file: https://cdn.discordapp.com/attachments/757985854588190731/1014526587410075708/vr-_01.20.00.apk

i tried to convert dex -> java but it showed these errors^
it didn't work on [pxb1988's dex2jar](https://github.com/pxb1988/dex2jar) too.

i dont know about it as well, but is it possible to fix?

### PR DESCRIPTION
**Pull request by Rabbit0w0**
~~This PR is not ready for merging. More tests are needed as I didn't test much.~~

This PR is ready for merging.

### CODE REVIEW

**Comment by Rabbit0w0** [comment]
@ThexXTURBOXx This approach is theoretically feasible to fix the problem in #25 . May you do some tests as I have not much time for this?

**Comment by ThexXTURBOXx** [comment]
Thank you very much for the PR. I have pulled it into `dev` for now. The PR will be automatically accepted when it's in `master`.
I see that this should help strings within methods, but will this also work on strings that are class members?

**Comment by Rabbit0w0** [comment]
Yo, member fields' values are initialized in <clinit>

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ThexXTURBOXx** [comment]
Thank you very much for the confirmation! I just looked at the disassembled and decompiled output and it looks like this:
grafik

Comparing with JADX output:
grafik

Maybe you can get rid of the supplementary variable `sb2` somehow? After that, I will merge into `master` ASAP :)

**Comment by ThexXTURBOXx** [comment]
I just merged it into `master` anyway - the new code is functionally correct and such optimisations can still be done at a later point. Thank you very much for your contribution! :)

**Comment by Rabbit0w0** [comment]
The existence of the new StringBuilder variable is basically due to the need of string concatenation. It just looks duplicated in such a context with an exisiting StringBuilder.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
